/**
 * `CONTEXT.md` — the file that makes the vault answerable.
 *
 * Pointing an agent at a folder of Markdown works, but it works *far* better
 * when the folder explains its own conventions: what `- [/]` means, that
 * `@name` is a colleague, that `#kudos` marks review-worthy moments. Without
 * that, an agent asked "what did Alice ship this quarter?" has to infer the
 * schema from examples and will quietly miss the in-progress marker.
 *
 * It's rewritten on every launch so it never drifts from the format the app
 * actually writes.
 */

export const CONTEXT_FILENAME = 'CONTEXT.md';

/**
 * The guide's content. A constant rather than a template: there is nothing
 * user-specific in it, and keeping it static means the file only changes when
 * the format does.
 */
export const CONTEXT_DOC = `# About this folder

This is a work journal maintained by **Task Tracker**, a desktop app that prompts
its user hourly to record what they are working on. Every file here is plain
Markdown and is safe to read directly.

This file is regenerated by the app on launch. Edit the day files freely — edits
are preserved — but changes to this file will be overwritten.

## Files

| Pattern         | What it is                                             |
| --------------- | ------------------------------------------------------ |
| \`YYYY-MM-DD.md\` | One workday: its task list and timestamped notes.      |
| \`YYYY-Www.md\`   | A generated weekly rollup (completed work, open items, kudos). |
| \`CONTEXT.md\`    | This file.                                             |

## Day file format

\`\`\`markdown
---
date: 2026-08-02
work_start: 09:00
work_end: 17:00
---

# Sunday, 2 August 2026

## Tasks

- [ ] Draft the migration RFC
- [/] Ship the rollback path
- [x] Review the release checklist

## Notes

- 10:15 — @alice unblocked the release single-handedly #kudos
- 14:00 — Deferred the cache work until the RFC lands #decision
\`\`\`

### Task status markers

| Marker  | Meaning                                        |
| ------- | ---------------------------------------------- |
| \`- [ ]\` | **Upcoming** — planned, not started.           |
| \`- [/]\` | **In progress** — actively being worked on.    |
| \`- [x]\` | **Completed.**                                 |

Open tasks (upcoming and in progress) roll over into the next day's file.
Completed tasks stay in the day that finished them — so to find when something
was completed, look for the day whose file marks it \`[x]\`.

### Notes

Each note is \`- HH:MM — text\` in local time, in the order it was written.

- \`@name\` refers to a **colleague**, often one of the user's direct reports.
  Handles are case-insensitive.
- \`#tag\` is a freeform label. Conventional tags:
  - \`#kudos\` — a moment worth remembering at review time. When answering
    questions about someone's performance, these are the highest-signal entries
    in the vault.
  - \`#blocker\` — something impeding progress.
  - \`#decision\` — a decision made and its reasoning.

## Answering questions about this vault

- **"What did I do last week?"** — read that week's \`YYYY-Www.md\` rollup first;
  fall back to the individual day files if it is missing.
- **"What has @alice been up to?"** — search all day files for \`@alice\`, and
  weight \`#kudos\` notes most heavily.
- **"Help me write my year-end review"** — gather every \`#kudos\` note plus all
  completed tasks across the period. The completed tasks are the *what*; the
  notes are the *why it mattered*.
- Absence of an entry means nothing was logged, **not** that nothing happened.
  Days outside the user's configured work window, weekends, and holidays are
  routinely empty.
`;
